<?php
/**
 * Copyright (c) 2024 Attila Sagi
 * @license http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper Magento\Framework\Escaper;
 * @var $viewModel \Space\CookieWarning\ViewModel\View\CookieWarning
 */

$viewModel = $block->getData('view_model');
?>

<?php if ($viewModel->isEnabled()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "cookieWarningModal": {}
            }
        }
    </script>

    <div id="cookie-warning-modal">
        <div class="content">
            Popup Content1
        </div>
    </div>

    <!--<div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'autoOpen': true,
            'title': 'Popup title',
            'responsive': true,
            'buttons': [{
                text: jQuery.mage.__('Submit1'),
                class: 'action'
            }]
        }}">
        <div class="content">
            Popup Content1
        </div>
    </div>-->
<?php endif; ?>
