<?php
/**
 * Copyright (c) 2024 Attila Sagi
 * @license http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper Magento\Framework\Escaper;
 * @var $viewModel \Space\CookieWarning\ViewModel\View\CookieWarning
 */

$viewModel = $block->getData('view_model');
?>

<?php if ($viewModel->isEnabled()): ?>
    <div id="cookie-warning-modal" class="cookie-warning-modal no-display">
        <div class="content">
            <div class="message">
                <?= $escaper->escapeHtml($viewModel->getCookieMessage(), ['strong']); ?>
            </div>
            <div class="link">
                <a href="<?= $escaper->escapeUrl($viewModel->getLinkUrl()) ?>"
                   title="<?= $escaper->escapeHtml($viewModel->getLinkText()) ?>">
                    <?= $escaper->escapeHtml($viewModel->getLinkText()) ?>
                </a>
            </div>
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            "*": {
                "cookieWarningModal": {
                    "acceptButtonText" : "<?= $escaper->escapeHtml($viewModel->getAcceptButtonText()) ?>",
                    "declineButtonText" : "<?= $escaper->escapeHtml($viewModel->getDeclineButtonText()) ?>"
                }
            }
        }
    </script>
<?php endif; ?>
