<?php
/**
 * Copyright (c) 2024 Attila Sagi
 * @license http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper Magento\Framework\Escaper;
 * @var $viewModel \Space\CookieWarning\ViewModel\View\CookieWarning
 * @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRender
 */

$viewModel = $block->getData('view_model');
?>

<style>
    .cookie-warning {
        position: fixed;
        z-index: 10;
    }

    .cookie-warning.top {
        top: 0;
        left: 0;
        right: 0;
    }

    .cookie-warning.bottom {
        bottom: 0;
        left: 0;
        right: 0;
    }

    .cookie-warning .content {
        padding: 1rem;
        background: #fff;
    }

    .cookie-warning .content h3 {
        margin-top: 0;
    }
</style>

<?php if ($viewModel->isEnabled()): ?>
    <div role="alertdialog"
         tabindex="-1"
         class="cookie-warning <?= $escaper->escapeHtml($viewModel->getPosition()) ?>"
         id="cookie-warning-block">
        <div role="document" class="content" tabindex="0">
            <h3><?= $escaper->escapeHtml($viewModel->getTitle()) ?></h3>
            <p class="message">
                <strong><?= $escaper->escapeHtml(__('We use cookies to make your experience better.')) ?></strong>
                <span><?= $escaper->escapeHtml($viewModel->getCookieMessage(), ['strong']) ?></span>
            </p>
            <p class="link">
                <a href="<?= $escaper->escapeUrl($viewModel->getLinkUrl()) ?>"
                   title="<?= $escaper->escapeHtml($viewModel->getLinkText()) ?>">
                    <span><?= $escaper->escapeHtml($viewModel->getLinkText()) ?></span>
                </a>
            </p>
            <div class="actions">
                <button id="btn-cookie-warning-accept" class="action allow primary">
                    <span><?= $escaper->escapeHtml($viewModel->getAcceptButtonText()) ?></span>
                </button>
                <button id="btn-cookie-warning-decline" class="action decline secondary">
                    <span><?= $escaper->escapeHtml($viewModel->getDeclineButtonText()) ?></span>
                </button>
            </div>
        </div>
    </div>
    <?=/* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'div#cookie-warning-block') ?>
    <script type="text/x-magento-init">
        {
            "#cookie-warning-block": {
                "cookieWarning": {
                    "declineButtonSelector": "#btn-cookie-warning-decline",
                    "acceptButtonText" : "<?= $escaper->escapeHtml($viewModel->getAcceptButtonText()) ?>",
                    "declineButtonText" : "<?= $escaper->escapeHtml($viewModel->getDeclineButtonText()) ?>"
                }
            }
        }
    </script>
<?php endif; ?>
